name: Deploy to Production

on: 
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clone source code
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: 22
        key: ${{ secrets.SSHKEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "."
        target: ${{ secrets.TARGET }}
    
    - name: Build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        key: ${{ secrets.SSHKEY }}
        script: |
              cd /tmp
              apt install wget -y
              wget https://go.dev/dl/go1.22.0.src.tar.gz
              tar -xvf go1.22.0.src.tar.gz
              mv go /usr/local
              echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.bashrc
              source ~/.bashrc
              go version
              go build -o ${{secrets.TARGET}}/bin/kmy ${{secrets.TARGET}}/

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        key: ${{ secrets.SSHKEY }}
        script: |
              touch "${{secrets.TARGET}}/bin/.env"
              printf "%s" "${{secrets.PRODUCTION_ENV}}" > "${{secrets.TARGET}}/bin/.env"
              systemctl stop api.quaythuockhanhmy.service
              systemctl disable api.quaythuockhanhmy.service
              rm /etc/systemd/system/api.quaythuockhanhmy.service
              systemctl daemon-reload
              systemctl reset-failed
              cp ${{secrets.TARGET}}/api.quaythuockhanhmy.service /etc/systemd/system/api.quaythuockhanhmy.service
              cat /etc/systemd/system/api.quaythuockhanhmy.service
              cd /etc/systemd/system
              systemctl daemon-reload
              systemctl start api.quaythuockhanhmy.service
              
